import Head from 'next/head'
import useSWRInfinite from 'swr/infinite'

import { useRef, useState } from 'react'

import {
  Button,
  Center,
  Code,
  Container,
  Group,
  Input,
  Kbd,
  Stack,
  Title,
  Text,
  useMantineTheme,
} from '@mantine/core'
import { useHotkeys } from '@mantine/hooks'
import { IconSearch } from '@tabler/icons-react'

import Release from '@/types/release'
import ReleaseCard from '@/components/ReleaseCard'
import HeaderBar from '@/components/HeaderBar'

import DotLoader from 'react-spinners/DotLoader'
import { useAutoAnimate } from '@formkit/auto-animate/react'

export default function Main() {
  const theme = useMantineTheme()

  const [parent] = useAutoAnimate()

  const fetcher = (url: string) => fetch(url).then((res) => res.json())
  const PAGE_SIZE = 15

  const [searchQuery, setSearchQuery] = useState('')
  const searchBarRef = useRef<HTMLInputElement>(null)
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value)
  }

  // allows filtering for author name, release name/date and exact release id
  const searchFilter = (releases: Release[]) => {
    return releases.filter(
      (el) =>
        el.author.login.toLowerCase().includes(searchQuery.toLowerCase()) ||
        el.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        el.id.toString() === searchQuery
    )
  }

  useHotkeys([['mod+K', () => searchBarRef.current?.focus()]])

  // fetches paginated results from github API
  const { data, mutate, size, setSize, isValidating, isLoading, error } = useSWRInfinite(
    (index) => `/api/releases?per_page=${PAGE_SIZE}&page=${index + 1}`,
    fetcher
  )

  const releases = searchFilter(data ? [].concat(...data) : [])
  const isEmpty = data?.[0]?.length === 0
  const isLoadingMore = isLoading || (size > 0 && data && typeof data[size - 1] === 'undefined')
  const isReachingEnd = isEmpty || (data && data[data.length - 1]?.length < PAGE_SIZE)
  const isRefreshing = isValidating && data && data.length === size

  if (error)
    return (
      <Center style={{ width: '100%', height: '80vh' }}>
        <Code>
          <Title px='sm' order={2}>
            Failed to load users
          </Title>
        </Code>
      </Center>
    )
  if (isLoading)
    return (
      <Center style={{ width: '100%', height: '80vh' }}>
        <DotLoader color={theme.colors.blue[6]} />
        <Code mx='xl'>
          <Title px={'sm'} order={2}>
            Loading...
          </Title>
        </Code>
      </Center>
    )
  if (!data)
    return (
      <Center style={{ width: '100%', height: '80vh' }}>
        <Code px='sm'>
          <Title order={2}>No data</Title>
        </Code>
      </Center>
    )

  return (
    <>
      <Head>
        <title>React Release Lister</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container p='md' size='sm' style={{ width: '85%' }}>
        <HeaderBar />
        <Stack align='stretch' justify='center' ref={parent}>
          <Input
            ref={searchBarRef}
            style={{
              display: 'flex',
              alignItems: 'center',
            }}
            icon={<IconSearch size='16' />}
            placeholder='Search'
            size='md'
            radius='md'
            rightSectionWidth={90}
            rightSection={<Kbd>⌘ + K</Kbd>}
            onChange={handleChange}
          />

          {releases.map((release: Release) => (
            <div key={release.id}>
              <ReleaseCard release={release} />
            </div>
          ))}

          <Group position='center' align='center'>
            <Text>
              showing {size} page(s) of {isLoadingMore ? '...' : releases.length} releases
            </Text>
            <Group>
              <Button disabled={isLoadingMore || isReachingEnd} onClick={() => setSize(size + 1)}>
                {isLoadingMore ? 'Loading...' : isReachingEnd ? 'No more issues' : 'Load more'}
              </Button>
              <Button disabled={isRefreshing} onClick={() => mutate()}>
                {isRefreshing ? 'Refreshing...' : 'Refresh'}
              </Button>
              <Button disabled={!size} onClick={() => setSize(0)} variant='light'>
                Clear
              </Button>
            </Group>

            {isEmpty ? <Text>No releases found</Text> : null}
          </Group>
        </Stack>
      </Container>
    </>
  )
}
